apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-cluster1
  region: ap-south-1

nodeGroups:
  - name: ng-1
    instanceType: t2.micro
    desiredCapacity: 2 
    ssh:
      publicKeyName: key1
  - name: ng-2
    instanceType: t2.small
    desiredCapacity: 1
    ssh:
      publicKeyName: key1
